### ISSUE TITLE
Launch the merch store through swag.cdnjs.com

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/swag-store#2]
We should launch the merch store through the cdnjs.com subdomain of `swag` so that users in the community know the store is official and not someone pretending to be us.

With the use of a third-party provider for the site, it may be easier to make `swag.cdnjs.com` a landing page that redirects users to the third-party site.

**Comment by MattIPv4** [comment]
Update to this: The plan is to launch the landing page housed within this repository with GitHub pages under `swag.cdnjs.com` which then points users to the third-party Spreadshirt store.

```
CNAME: swag.cdnjs.com -> cdnjs.github.io
```

This is easier than creating a custom page to embed the store directly as this will still have to take users off-domain to complete the checkout process. Additionally, it would not allow for meta tags to be loaded properly and so would reduce SEO.

cc @thomasdavis

**Comment by PeterDaveHello** [comment]
@ryankirkman can you help with this?

**Comment by xtuc** [comment]
I added the record.

**Comment by MattIPv4** [comment]
Amazing, thank you!
